import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AlgorithmProvider } from "@/contexts/AlgorithmContext";

const inter = Inter({
  subsets: ["latin"],
  weight: ["500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <AlgorithmProvider>{children}</AlgorithmProvider>
      </body>
    </html>
  );
}
